README.md, recipe/meta.yaml
=> Updated leafmap feedstock to v0.1.0

recipe/meta.yaml
=> Updated leafmap feedstock to v0.2.0

.azure-pipelines/azure-pipelines-linux.yml, recipe/meta.yaml
=> Updated feedstock to v0.3.0

recipe/meta.yaml
=> Updated feedstock to v0.3.1

recipe/meta.yaml
=> Updated feedstock to v0.3.3

recipe/meta.yaml
=> Prep for v0.3.4

README.md, recipe/meta.yaml
=> Update feedstock to v0.4.1

recipe/meta.yaml
=> Updated feedstock to v0.5.0

.ci_support/linux_64_.yaml, recipe/meta.yaml
=> Updated  leafmap feedstock to v0.5.2

recipe/meta.yaml
=> Updated leafmap feedstock to v0.5.3

.azure-pipelines/azure-pipelines-linux.yml, .gitattributes, .scripts/build_steps.sh, .scripts/run_docker_build.sh, build-locally.py, recipe/meta.yaml
=> Updated feedstock to v0.5.4

README.md, recipe/meta.yaml
=> Updated leafmap feedstock to v0.5.5

recipe/meta.yaml
=> Updated feedstock to v0.6.0

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_.yaml, .scripts/build_steps.sh, recipe/meta.yaml
=> Updated feedstock to v0.6.1

recipe/meta.yaml
=> Updated feedstock to v0.7.0

recipe/meta.yaml
=> Updated feedstock to v0.7.1

recipe/meta.yaml
=> Updated feedstock to v0.7.2

recipe/meta.yaml
=> Updated to v0.7.3

recipe/meta.yaml
=> Updated feedstock to v0.7.4

recipe/meta.yaml
=> Updated feedstock to v0.7.5

recipe/meta.yaml
=> Updated feedstock to v0.7.7

recipe/meta.yaml
=> Updated feedstock to v0.8.1

README.md, recipe/meta.yaml
=> Updated feedstock to v0.9.0

recipe/meta.yaml
=> Removed geopandas and localtileserver

recipe/meta.yaml
=> Updated to v0.9.2

recipe/meta.yaml
=> Updated to v0.9.3

recipe/meta.yaml
=> Removed mapclassify

recipe/meta.yaml
=> Updated to v0.9.6

.scripts/build_steps.sh, README.md, recipe/meta.yaml
=> Update to v0.18.1

recipe/meta.yaml
=> Update to v0.20.3

recipe/meta.yaml
=> Update to v0.21.0

recipe/meta.yaml
=> Update to v0.21.3

recipe/meta.yaml
=> Update to v0.22.0

recipe/meta.yaml
=> Pin JupyterLab version

recipe/meta.yaml
=> leafmap v0.23.0

recipe/meta.yaml
=> Update leafmap to v0.29.0

README.md, recipe/meta.yaml
=> Add support for JupyterLab 4.x

recipe/meta.yaml
=> leafmap v0.31.0

recipe/meta.yaml
=> Add ipyvuetify

recipe/meta.yaml
=> Update numpy version

recipe/meta.yaml
=> Leafmap v0.36.7

recipe/meta.yaml
=> Leafmap v0.36.8

recipe/meta.yaml
=> Add pmtiles

recipe/meta.yaml
=> Leafmap v0.36.9

recipe/meta.yaml
=> Leafmap v0.38.0

.scripts/build_steps.sh, azure-pipelines.yml, recipe/meta.yaml
=> leafmap v0.38.6

README.md, recipe/meta.yaml
=> leafmap v0.38.8

recipe/meta.yaml
=> Update Python min

recipe/meta.yaml
=> Add deps for NASA OPERA
